### PR TITLE
remove legacy CSW server implementation

### PR DESCRIPTION
**Pull request by tomkralidis**
Covers #134.

@amercader should we remove the [cswinfo](http://docs.ckan.org/projects/ckanext-spatial/en/latest/csw.html#cswinfo) entry point as well?  If yes, I will remove and squash into this PR.

### CODE REVIEW

**Comment by davidread** [comment]
Merging, since @amercader is happy for this to happen and the code deletions looks good. Thanks @tomkralidis :+1:

**Comment by tomkralidis** [comment]
Thanks @davidread. Is the cswinfo entry point legacy also (docs say it is) Should we remove this too (I'll do another PR)

**Comment by davidread** [comment]
TBH I still use cswinfo for making simple CSW requests on the command-line. I don't see any harm in having it kick around... Unless you can suggest an improved command-line tool for this?

**Comment by tomkralidis** [comment]
@davidread :+1 good idea let's keep. Only asking because it is labelled legacy in the docs. Should we update the docs?

**Comment by davidread** [comment]
It is a pretty rubbish tool though, so I'm in two minds... What do you think @amercader ?

**Comment by tomkralidis** [comment]
If we keep it, I've issued this PR: https://github.com/ckan/ckanext-spatial/pull/137

If not, I will close https://github.com/ckan/ckanext-spatial/pull/137 and issue a PR that removes the cswinfo entry point.

**Comment by amercader** [comment]
I tend to favour removing unmaintained code, especially if it's as old as this one, but if you use it from time to time I'm happy to keep it. If I need to query CSW endpoints I generally use OWSLib directly on iPython.

**Comment by davidread** [comment]
You're right, using owslib in python repl is fine. Go on then, let's get rid of cswinfo!

**Comment by tomkralidis** [comment]
I'll issue another PR then

**Comment by tomkralidis** [comment]
New PR at #141

**Pull request merged**
