### PR TITLE
Fix IOError when opening metadata schema #174

### PR DESCRIPTION
**Pull request by LondonAppDev**
Fix for https://github.com/ckan/ckanext-spatial/issues/174

### CODE REVIEW

**Comment by amercader** [comment]
@LondonAppDev thanks for this. I'm not sure if these validation profiles have been used recently so any work on them is welcomed. It seems like you need to update this `resource_stream` usage as well:

https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/controllers/api.py#L76

@davidread perhaps you know more about these schematrons than I do.

**Comment by davidread** [comment]
Both variants of the resource_stream syntax work for me.
```
from pkg_resources import resource_stream
with resource_stream('ckanext.spatial.validation', 'xml/schematron/iso_svrl_for_xslt1.xsl') as f: print f.read()
with resource_stream('ckanext.spatial', 'validation/xml/schematron/iso_svrl_for_xslt1.xsl') as f: print f.read()
```
But I am happy for this change if it helps other people.

**Comment by LondonAppDev** [comment]
Thanks @amercader and @davidread. I'm pushing a change to the `controllers/api.py` file as @amercader suggested. Hoping that will fix the failed tests.

Although I am a bit confused with how `resource_stream` is working and why it would work for @davidread but not for me. I'm wondering if it's related to the `PATHS`...

**Comment by LondonAppDev** [comment]
Hey @amercader and @davidread, I made the change and the tests are passing. Would you kindly be able to approve or give me feedback for this PR?

Thanks in advance.

**Comment by davidread** [comment]
Thanks

**Pull request merged**
