### PR TITLE
Accept geometry with 4 points only with a warning

### PR DESCRIPTION
**Pull request by miguelbgouveia**
Accepting in case of solr search backend, geometry Polygon with only 4 points defined. Send a warning instead of error.

### CODE REVIEW

**Comment by amercader** [comment]
@miguelbgouveia sorry, but a Polygon representing a Bounding Box in GeoJSON with 4 sets of coordinates is incorrect.

The [GeoJSON](http://geojson.org/geojson-spec.html#polygon) spec says:

> 2.1.6. Polygon
>
> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays. For > Polygons with multiple rings, the first must be the exterior ring and any others must be interior rings or > holes.

and

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points). Though a LinearRing is not explicitly represented as a GeoJSON geometry type, it is referred to in the Polygon geometry type definition.

First and last points always need to be the same, otherwise the box is not closed.

**Comment by miguelbgouveia** [comment]
I known that Polygon in geoJSON must be defined by 5 points. But since that in ckan we only need the 4 first points I think it is better to send a warning that just interrupt the process. And the warning log in this PR is more explicit in the type of format problem since it said that missing a geographic point.

**Comment by amercader** [comment]
We should not encourage the use of bad metadata :) 
We can improve the current log message to something like `'Solr backend only supports bboxes (Polygons with 5 points), ignoring geometry {0}'`

**Comment by miguelbgouveia** [comment]
Yes maybe that resolve the problem for the ones that are not familiar with geoJSON. I will close this PR and create another with your suggestion.

**Pull request closed without merging**
