### PR TITLE
[#191] skip dataset during import

### PR DESCRIPTION
**Pull request by knudmoeller**
* Allows `get_package_dict()` to return `'skip'` in cases where a dataset should, upon closer inspection, not be imported after all.
* `'skip'` will be caught in `import_stage()`, which then returns `'unchanged'`, following the documentation at https://github.com/ckan/ckanext-harvest#the-harvesting-interface.
* **Note:** This setup assumes an alternative implementation of `get_package_dict()`, e.g. in a sub-class of `SpatialHarvester`.

### CODE REVIEW

**Comment by amercader** [comment]
Thanks @knudmoeller this looks good. Would you mind documenting this behaviour in the docs?

https://github.com/ckan/ckanext-spatial/blob/master/doc/harvesters.rst#customizing-the-harvesters

**Comment by knudmoeller** [comment]
@amercader Sorry, I forgot about this. I have now added the relevant documentation. Any chance this PR can be merged?

**Comment by knudmoeller** [comment]
There are lots of completely unrelated failing tests. I'm not sure there is anything on my side I can do to make them pass.

**Comment by knudmoeller** [comment]
The PR is quite old, so I'm closing it. I will submit a new PR with an updated version based on the current version of ckanext-spatial.

**Pull request closed without merging**
