### PR TITLE
[#162] Allow use of WMS layer in extent map

### PR DESCRIPTION
**Pull request by etj**

### CODE REVIEW

**Comment by davidread** [comment]
Code looks fine. Apologies if I'm being ignorant, but why would someone choose to put a base map in a WMS layer?

**Comment by etj** [comment]
Good question :) I was porting an old CKAN instance to a later version, and the original setup used WMS, so I simply needed to replicate that environment. 

Anyway, I created the PR bc it simply offers one more choice to the CKAN admin.

**Comment by davidread** [comment]
@etj thanks for that.

@amercader it's up to you as maintainer

**Comment by amercader** [comment]
I'd never advocate this use of WMS but if it's helpful for migrating legacy apps I'm happy to merge it the code is quite straight-forward. Thanks @etj

**Pull request merged**
